# Generated by Django 6.0.1 on 2026-06-18 06:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_cost', models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=10)),
                ('single_cost_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=4)),
            ],
            options={
                'verbose_name': 'Настройки центра',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('capacity', models.PositiveSmallIntegerField(default=10, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('subscription_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Стоимость абонемента')),
                ('trial_cost', models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=10, verbose_name='Пробное занятие')),
                ('min_age', models.PositiveSmallIntegerField(default=3, verbose_name='Мин. возраст')),
                ('max_age', models.PositiveSmallIntegerField(default=12, verbose_name='Макс. возраст')),
                ('gender', models.CharField(blank=True, choices=[('', 'Любой'), ('boy', 'Мальчик'), ('girl', 'Девочка')], default='', max_length=10, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Аудит',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KanbanTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'ToDo'), ('in_progress', 'InProgress'), ('done', 'Done')], default='todo', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Канбан',
            },
        ),
        migrations.CreateModel(
            name='MaterialPurchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед.')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого')),
                ('purchase_date', models.DateField(verbose_name='Дата закупки')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Поставщик')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction')),
            ],
            options={
                'verbose_name': 'Закупка материалов',
                'verbose_name_plural': 'Закупки материалов',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст')),
                ('published_date', models.DateField(default=django.utils.timezone.localdate)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('boy', 'Мальчик'), ('girl', 'Девочка')], default='boy', max_length=10, verbose_name='Пол')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('registration_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата регистрации')),
                ('directions', models.ManyToManyField(blank=True, related_name='students', to='core.direction', verbose_name='Направления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.parent', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('subscription', 'Абонемент'), ('trial', 'Пробное'), ('single', 'Разовое'), ('transfer_debit', 'Перенос (списание)'), ('transfer_credit', 'Перенос (зачисление)'), ('other', 'Другое')], default='subscription', max_length=30, verbose_name='Тип')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.direction')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='SubDirection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdirections', to='core.direction', verbose_name='Основное направление')),
            ],
            options={
                'verbose_name': 'Поднаправление',
                'verbose_name_plural': 'Поднаправления',
                'ordering': ['parent__name', 'name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='subdirections',
            field=models.ManyToManyField(blank=True, related_name='students', to='core.subdirection', verbose_name='Поднаправления'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Действует с')),
                ('end_date', models.DateField(verbose_name='Действует по')),
                ('total_lessons', models.PositiveSmallIntegerField(help_text='Заполняется автоматически при покупке по расписанию', verbose_name='Всего занятий')),
                ('carried_lessons', models.PositiveSmallIntegerField(default=0, help_text='Занятия, перенесённые с прошлого периода', verbose_name='Перенесённые занятия')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('expired', 'Завершён'), ('cancelled', 'Отменён')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.direction')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='core.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.student')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приёма')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('rate_per_lesson', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Базовая ставка для расчёта зарплаты', max_digits=10, verbose_name='Ставка за занятие')),
                ('directions', models.ManyToManyField(blank=True, related_name='teachers', to='core.direction', verbose_name='Направления')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SingleLesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('lesson_type', models.CharField(choices=[('single', 'Разовое'), ('makeup', 'Отработка')], default='single', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Сумма при переносе/отработке', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.direction')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_lessons', to='core.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher')),
            ],
            options={
                'verbose_name': 'Разовое занятие',
                'verbose_name_plural': 'Разовые занятия',
                'ordering': ['-lesson_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='core.classroom')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='core.direction')),
                ('subdirection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='core.subdirection')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='core.teacher')),
            ],
            options={
                'verbose_name': 'Слот расписания',
                'verbose_name_plural': 'Расписание',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_date', models.DateField(verbose_name='Дата занятия')),
                ('present', models.BooleanField(default=False, verbose_name='Был')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Примечание')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.direction')),
                ('schedule_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.scheduleslot')),
                ('single_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.singlelesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.student')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='core.subscription')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-lesson_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('schedule_slot__isnull', False)), fields=('student', 'lesson_date', 'schedule_slot'), name='unique_schedule_attendance'), models.UniqueConstraint(condition=models.Q(('single_lesson__isnull', False)), fields=('student', 'single_lesson'), name='unique_single_attendance')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_date', models.DateField(verbose_name='Дата')),
                ('exception_type', models.CharField(choices=[('substitution', 'Замена преподавателя'), ('cancel', 'Отмена')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='core.scheduleslot')),
                ('substitute_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutions', to='core.teacher')),
            ],
            options={
                'verbose_name': 'Исключение в расписании',
                'verbose_name_plural': 'Исключения в расписании',
                'unique_together': {('lesson_date', 'schedule_slot')},
            },
        ),
    ]
