# Generated by Django 6.0.1 on 2026-07-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teacher_payroll_and_creative_directions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherpayrollperiod',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teacherpayrollperiod',
            name='deduct_directions',
        ),
        migrations.RemoveField(
            model_name='teacherpayrollperiod',
            name='teacher',
        ),
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_schedule_attendance',
        ),
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_single_attendance',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='is_creative',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='payroll_deduction',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='manual_bonus',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='rate_per_lesson',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='revenue_percent',
        ),
        migrations.DeleteModel(
            name='TeacherPayrollPeriod',
        ),
    ]
