# Generated by Django 6.0.1 on 2026-07-01 09:12

import django.db.models.deletion
from django.db import migrations, models


def backfill_individual_slot_students(apps, schema_editor):
  ScheduleSlot = apps.get_model('core', 'ScheduleSlot')
  Student = apps.get_model('core', 'Student')
  AttendanceRecord = apps.get_model('core', 'AttendanceRecord')

  for slot in ScheduleSlot.objects.filter(
      direction__lesson_type='individual', student__isnull=True,
  ).select_related('direction'):
      first = Student.objects.filter(directions=slot.direction_id).order_by('name').first()
      if first:
          slot.student_id = first.id
          slot.save(update_fields=['student_id'])

  for slot in ScheduleSlot.objects.filter(
      direction__lesson_type='individual', student__isnull=False,
  ):
      AttendanceRecord.objects.filter(schedule_slot_id=slot.id).exclude(
          student_id=slot.student_id,
      ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_simplify_teacher_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Обязательно для индивидуальных занятий', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='core.student', verbose_name='Ученик'),
        ),
        migrations.RunPython(backfill_individual_slot_students, migrations.RunPython.noop),
    ]
